### ISSUE TITLE
The "--tile-rows=1 --tile-cols=1" gives 1x2 (wxh) tiles

### ISSUE THREAD

**Issue by ycho** [xiph/rav1e#1704] opened 2019-09-26 17:22 UTC
There seems to have bug in tiling.
I set "--tile-rows=1 --tile-cols=1"
as in "./target/release/rav1e /Users/yushin/Downloads/crowd_run-1frame.y4m -o test.ivf -r test_rec.y4m --quantizer=150 --speed=10     --limit=1 --tune=Psnr --tile-rows=1 --tile-cols=1"
Then, the output is 1x2 (wxh) tiles as below:

https://people.xiph.org/~yushin/data/crowd_run-1frame.y4m

<img width="970" alt="Screen Shot 2019-09-26 at 10 20 37 AM" src="https://user-images.githubusercontent.com/10123259/65710193-5aab8200-e047-11e9-9a1b-dbde2f7083e0.png">

**Comment by shssoichiro** [comment] 2019-09-26 17:37
How did you generate your crowd_run-1frame.y4m (or can you upload it)? When I use `target/debug/rav1e -o /dev/null /Users/jholmer/Downloads/crowd_run_1080p50.y4m -l 1 --tile-rows=1 --tile-cols=1` using the crowd_run from media.xiph.org I get 1 tile.

**Comment by ycho** [comment] 2019-09-26 17:43
> How did you generate your crowd_run-1frame.y4m (or can you upload it)? When I use `target/debug/rav1e -o /dev/null /Users/jholmer/Downloads/crowd_run_1080p50.y4m -l 1 --tile-rows=1 --tile-cols=1` using the crowd_run from media.xiph.org I get 1 tile.
> 
> Edit: Or are you using the 2160p crowd_run?

https://people.xiph.org/~yushin/data/crowd_run-1frame.y4m

**Comment by shssoichiro** [comment] 2019-09-26 17:49
This is not a bug, actually it is required to conform to the AV1 spec. We have this code that sets a minimum number of tiles based on frame resolution and frame rate:

```rust
// Implements restriction in Annex A of the spec.
// Unlike the other restrictions, this one does not change
// the header coding of the tile rows/cols.
let min_tiles_ratelimit_log2 =
  min_tiles_log2.max(
    (((frame_width * frame_height) as f64 * frame_rate / MAX_TILE_RATE
      + 0.5) as usize)
      .ilog(),
  );
```

**Comment by shssoichiro** [comment] 2019-09-26 17:54
As part of https://github.com/xiph/rav1e/pull/1701 I'll add a note to the CLI parameters to let users know there are limitations on tiles based on video resolution.

**Comment by xiphmont** [comment] 2019-09-26 22:17
Having looked at the tiling code before, the --tile-rows= and --tile-cols= are treated as minimums.  TD wrote that code I believe, you probably want to ping him about it.

**Comment by shssoichiro** [comment] 2019-09-27 01:03
There are also maximums that can be enforced e.g. for low resolution videos.

**Comment by ycho** [comment] 2019-09-30 19:32
> This is not a bug, actually it is required to conform to the AV1 spec. We have this code that sets a minimum number of tiles based on frame resolution and frame rate:
> 
> ```rust
> // Implements restriction in Annex A of the spec.
> // Unlike the other restrictions, this one does not change
> // the header coding of the tile rows/cols.
> let min_tiles_ratelimit_log2 =
>   min_tiles_log2.max(
>     (((frame_width * frame_height) as f64 * frame_rate / MAX_TILE_RATE
>       + 0.5) as usize)
>       .ilog(),
>   );
> ```

So, for the frame size 3840x2160 that I tried, tiling by 1x2 (wxh) is expected behavior?

**Comment by shssoichiro** [comment] 2019-09-30 19:55
Correct.

**Comment by shssoichiro** [comment] 2019-10-01 13:35
Going to close this per the help message update in #1701.

**Closed by shssoichiro** 2019-10-01 13:35 UTC
Labels: bug
