### ISSUE TITLE
--second-pass broken

### ISSUE THREAD

**Issue by moisespr123** [xiph/rav1e#2231] opened 2020-04-12 21:02 UTC
Using the master branch:

```
Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.
The application panicked (crashed).
Error submitting pass data in second pass.: Failure
in src\bin\rav1e.rs, line 124
thread: main
```

First pass works fine and the file is generated.

**Comment by lu-zero** [comment] 2020-04-12 21:07
Please provide the command line you used.

**Comment by lu-zero** [comment] 2020-04-12 21:12
It might be a dupe of https://github.com/xiph/rav1e/issues/2188

**Comment by moisespr123** [comment] 2020-04-12 21:19
First pass:
 `Command Line: "D:\Temp\y4m-part-000000.y4m" --first-pass "D:\Temp\y4m-part-000000.ivf.first-pass-arg-output" -o "D:\Temp\y4m-part-000000.ivf.first-pass.ivf"  --quantizer 100 -s 6 -i 12 -I 240 --tune psychovisual --primaries unspecified --content_light 0,0 --matrix unspecified --range Limited --transfer unspecified -v --psnr`

Second pass:
`Command Line: "D:\Temp\y4m-part-000000.y4m" --second-pass "D:\Temp\y4m-part-000000.ivf.first-pass-arg-output" -o "D:\Temp\y4m-part-000000.ivf"  --quantizer 100 -s 6 -i 12 -I 240 --tune psychovisual --primaries unspecified --content_light 0,0 --matrix unspecified --range Limited --transfer unspecified -v --psnr`

**Comment by lu-zero** [comment] 2020-04-12 21:35
You have to set the bitrate, confirmed to be a duplicate of #2188

**Closed by lu-zero** 2020-04-12 21:35 UTC
