### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#1202] opened 2019-04-10 06:16 UTC
Prerequisites:
- [x] Have a nasm-rs release we can use
- [x] Publish a `0.1.0` for `ivf` and `rav1e`

**Comment by rzumer** [comment] 2019-04-27 13:52
This seems like a duplicate of #491. If that's the case, I recommend editing the opening post in that issue with the checklist appended, and closing this one.

**Comment by lu-zero** [comment] 2019-04-27 14:28
It is not :)

**Comment by rzumer** [comment] 2019-04-27 14:29
Then can you detail the difference, besides the fact that this issue is specifying a particular repository?

**Closed** 2020-07-06 19:11 UTC
Labels: enhancement
