### ISSUE TITLE
Visible desyncs in some 4K clips

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#2453] opened 2020-07-15 20:20 UTC
Still researching the cause, and will update this issue as I figure it out.

Commit: https://github.com/xiph/rav1e/commit/01052fc7121114904501f81f52a234c96373829d
Sample: https://drive.google.com/file/d/1UrXkq8pDKBFhq8wojWd7W_VOBOIY-pb2/view?usp=sharing (3840x2160)
Command lines and output:
```
$ cargo run --bin rav1e --release -- surfing_50f.y4m -s 10 -r surfing_50f_rec.y4m -o surfing_50f.ivf
$ dav1d -i surfing_50f.ivf -o surfing_50f_dec.y4m
$ cmp <(tail -n+2 surfing_50f_dec.y4m) <(tail -n+2 surfing_50f_rec.y4m)
/dev/fd/63 /dev/fd/62 differ: byte 318238388, line 19122
```

Blocky artifacts pop in and out in the decoded output, so this affects image quality significantly. Definitely should block any release, assuming it is not also present in past ones. Visible artifacts appear concentrated in the top-right corner of the visible part of the frame in this sample.

Occurs in both constant quantizer and single-pass bitrate target mode. Could reproduce down to speed 7, with very visible artifacts at levels 9 and 10.

**Comment by rzumer** [comment] 2020-07-15 23:27
Bisect points to 5d7599c9bbdcbd1ff44d100d806003bd7021544d.

**Comment by ycho** [comment] 2020-07-16 04:12
Hey- if possible, could you revert the suspected commit 5d7599c9bbdcbd1ff44d100d806003bd7021544d and test please? That way, we can confirm that the bisected commit is the sole cause.

**Comment by rzumer** [comment] 2020-07-16 13:26
@ycho As expected, reverting fixes the desync.

**Comment by ycho** [comment] 2020-07-16 16:22
> @ycho As expected, reverting fixes the desync.

Oh, indeed. Thanks a lot for testing this again!

**Comment by ycho** [comment] 2020-07-16 16:24
@barrbrain , Hey- I think this issue is wanting your help! :)

**Comment by rzumer** [comment] 2020-07-22 16:16
Forgot to mention in writing, the issue is present in v0.3.2. In the future I recommend avoiding merging non-bugfixes for patch releases.

**Comment by rzumer** [comment] 2020-07-23 18:42
We found that enabling CDEF while disabling loop restoration (done at speed level 10) is another cause. It's likely that there is a bug at that level that was exposed by the RDO commit.

**Comment by ycho** [comment] 2020-08-10 08:57
Please test with applying https://github.com/xiph/rav1e/pull/2488 , since this can be possible culprit as @barrbrain stated.

**Comment by ycho** [comment] 2020-08-10 09:16
It seems the test input, https://0x0.st/ivbO.zip, does not have real .y4m file?
Download and unzipped it, then I have: 'ivbO.zip.cpgz', 441 bytes?

**Comment by rzumer** [comment] 2020-08-10 13:22
> This is possibly related to #2453, which is a desync case at speeds 9 & 10. These are the only presets for which enable_inter_tx_split is set.

That desync is reproducible on all speed levels >=7 at least, so I guess not.

>  Download and unzipped it, then I have: 'ivbO.zip.cpgz', 441 bytes?
For some reason the file host deleted it.

**Comment by ycho** [comment] 2020-08-10 20:46
> Please test with applying #2488 , since this can be possible culprit as @barrbrain stated.
> 
> Another fact I expect is that, our rdo-based mode decision does not include skip case for intra mode, but we skip enforcing feature (
> 
> https://github.com/xiph/rav1e/blob/fe61a877488da642ae8c0844d31ff62f8b2ba66e/src/encoder.rs#L2314
> , [3bf1c46](https://github.com/xiph/rav1e/commit/3bf1c46359ed61c9622f0f6fe8251c5a33885977)), which partially achieves skipped intra mode block. And this converted-to-skip intra block can happen in a inter frame, which again possibly can update wrong tx size context as I reported in #2488.
> 
> In addition, the merged commit, [c41325d](https://github.com/xiph/rav1e/commit/c41325d024b9a77c661b8ad917418c75ac777930), can be related as well. Since this commit fix to correctly update tx_size context for such case, i.e. 'converted-to-skip intra block'.
> 
> So, testing with rebasing upto [c41325d](https://github.com/xiph/rav1e/commit/c41325d024b9a77c661b8ad917418c75ac777930), (which does not include open-partition yet) and cherry-pick [8394849](https://github.com/xiph/rav1e/commit/83948495689a08e89b029dcd6c0ba77baf7a37d1) is recommended.

FYI: Both two commits I've recommended to test with has been merged, so if you'd like just rebase on current master head will include all new fixes from my side.

**Comment by rzumer** [comment] 2020-08-10 22:10
Unfortunately the desync is still present on master.

**Comment by ycho** [comment] 2020-08-10 22:12
> Unfortunately the desync is still present on master.

Alas... but thanks a lot for trying this promptly! I wanted to help.

**Comment by ycho** [comment] 2020-08-10 23:08
./target/release/rav1e ~/Downloads/surfing.y4m  -o test.ivf -r test_rec.y4m --speed=10 --limit=50


>  Encoding settings: keyint_min=12 keyint_max=240 quantizer=100 bitrate=0 min_quantizer=0 low_latency=false tune=Psychovisual rdo_lookahead_frames=40 min_block_size=32x32 max_block_size=32x32 multiref=true fast_deblock=true reduced_tx_set=true tx_domain_distortion=false tx_domain_rate=false encode_bottomup=false rdo_tx_decision=false prediction_modes=Simple include_near_mvs=false no_scene_detection=false cdef=true use_satd_subpel=false non_square_partition=false enable_timing_info=false fine_directional_intra=true
>  CPU Feature Level: AVX2
>  Using 1 tile
>  encoded 50/50 frames, 0.244 fps, 29831.88 Kb/s, est. size: 7.11 MB, est. time: 0s,  elap. time: 3m 24s                     
>  ----------
>  Key frame:             1 | avg QP:  79.00 | avg size:     140 B
>  Inter frame:          49 | avg QP: 134.00 | avg size:  152200 B
>  Intra only frame:      0 | avg QP:   0.00 | avg size:       0 B
>  Switching frame:       0 | avg QP:   0.00 | avg size:       0 B

There is 1st difference at frame 15 (starting from 1) and more at following frames.

**Comment by ycho** [comment] 2020-08-11 01:31
With hard coded disabling fine_directional_intra_preset(), i.e. return false, the desync is persistent.

./target/release/rav1e ~/Downloads/surfing.y4m  -o test.ivf -r test_rec.y4m --speed=10 --low_latency --rdo-lookahead-frames=1

So, as rzumer just changed the title of this issuem fine dir intra pred does not seem the cause of desync.

**Closed** 2020-08-14 06:34 UTC
Labels: BLOCKER, bug, desync
