### ISSUE TITLE
Possible issues with AVX2 CPU's on Windows?

### ISSUE THREAD

**Issue by moisesmcardona** [xiph/rav1e#1618] opened 2019-08-30 23:14 UTC
We are discussing the rav1e issue #1615 on the AV1 Discord chat (https://discord.gg/b6gVub5).

We identified that those with old CPU's are not experiencing any issues.

Sor far reported is as follows:

## Works with
* Intel i5-3320m
* Intel Core 2 Quad q9300

# Not working with
* Intel i7-6700
* AMD Ryzen 7 2700X

We are assuming that rav1e is working on CPU's that lacks the AVX2 instruction set.

This seems to only affect Windows builds. I personally was able to run rav1e on Linux using WSL, compiled from the same source code. On Windows, neither building directly from the VS2019 terminal nor MinGW worked. The build is successful, but it gives the problem from the above-referenced issue.

**Comment by dwbuiten** [comment] 2019-08-30 23:16
This sounds more like info you should add to #1615 than a new bug, AFAICT?

(Also TIL there is an AV1 Discord...)

**Comment by lu-zero** [comment] 2019-08-31 08:24
Could you please set the env RAV1E_CPU_TARGET to "rust".
e.g.:
```
export RAV1E_CPU_TARGET="rust"
```
if you are using msys2

**Comment by moisesmcardona** [comment] 2019-08-31 11:20
> Could you please set the env RAV1E_CPU_TARGET to "rust".
> e.g.:
> 
> ```
> export RAV1E_CPU_TARGET="rust"
> ```
> 
> if you are using msys2

Unfortunately, it doesn't work.

**Comment by lu-zero** [comment] 2019-08-31 13:26
Try building with:
```
cargo build --release --no-default-features --features=binaries
```

**Comment by jamrial** [comment] 2019-08-31 23:48
I can confirm that compiling with `cargo build --no-default-features --features=binaries` gets rid of the crash.

**Comment by moisesmcardona** [comment] 2019-09-01 01:22
Can also confirm it fixes the issue.

**Comment by 1480c1** [comment] 2019-09-01 03:42
Is there a way to disable avx2 only? (I'm assuming that avx2 functions are causing the problems) I'm not very familiar with cargo build's commands and features

_Originally posted by @1480c1 in https://github.com/m-ab-s/media-autobuild_suite/pull/1373#issuecomment-526882950_

**Comment by ImportTaste** [comment] 2019-09-01 03:45
If I'm not mistaken, the purpose to @lu-zero's question was to confirm whether or not this pending fix in PR #1621 would have an effect: https://github.com/rust-av/rav1e/commit/2446895a3f094225eeaf75106e46cab5ed4cbd97

**Comment by lu-zero** [comment] 2019-09-01 09:47
I started looking at it since the current state is a bit of a in between exposing the ability to select the cpu features to the user and hiding it completely.

There is consensus on not exposing this at the API level, so that PR just does that but doesn't change the (probably broken now we know) dispatch functionality.

This issue tracks the fact there is at least 1 avx2 nasm function misbehaving on windows, I'll open another issue about investigating what's wrong with the current dispatch code soon.

**Comment by lu-zero** [comment] 2019-09-01 16:01
Thanks to @jamrial we pinned down the problem to the get_satd avx2 implementation.

**Comment by lu-zero** [comment] 2019-09-03 06:44
This one should be addressed now, right?

**Comment by lu-zero** [comment] 2019-09-03 06:45
it is a duplicate of #1618

**Closed by lu-zero** 2019-09-03 06:45 UTC
Labels: SIMD, bug
