### ISSUE TITLE
Build of patched rav1e 0.3.4 on Apple Silicon fails

### ISSUE THREAD

**Issue by fxcoudert** [xiph/rav1e#2626] opened 2020-12-29 09:20 UTC
Hi, I'm trying to make rav1e work on Apple Silicon for Homebrew: https://github.com/Homebrew/homebrew-core/pull/67767

I'm using the latest stable release (rav1e 0.3.4) with a backport of your patch for Apple Silicon (https://github.com/xiph/rav1e/pull/2602) and the rust 1.49.0-beta compiler. However, this fails to build, with the following error:

```
   Compiling rav1e v0.3.4 (/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4)
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to run custom build command for `rav1e v0.3.4 (/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4)

Caused by:
  process didn't exit successfully: `/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4/target/release/build/rav1e-223265922b3f8220/build-script-build` (exit code: 1)
  --- stdout
  cargo:rustc-cfg=asm_neon
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("aarch64-apple-darwin")
  CC_aarch64-apple-darwin = None
  CC_aarch64_apple_darwin = None
  HOST_CC = None
  CC = Some("clang")
  CFLAGS_aarch64-apple-darwin = None
  CFLAGS_aarch64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-apple-darwin" "-I" "." "-I" "/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4/target/release/build/rav1e-b6250c85918f733a/out" "-Wall" "-Wextra" "-o" "/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4/target/release/build/rav1e-b6250c85918f733a/out/src/arm/64/mc.o" "-c" "src/arm/64/mc.S"
  cargo:warning=error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
  exit code: 1
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-apple-darwin" "-I" "." "-I" "/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4/target/release/build/rav1e-b6250c85918f733a/out" "-Wall" "-Wextra" "-o" "/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4/target/release/build/rav1e-b6250c85918f733a/out/src/arm/64/itx.o" "-c" "src/arm/64/itx.S"
  cargo:warning=error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
  exit code: 1

  --- stderr


  error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-apple-darwin" "-I" "." "-I" "/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4/target/release/build/rav1e-b6250c85918f733a/out" "-Wall" "-Wextra" "-o" "/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4/target/release/build/rav1e-b6250c85918f733a/out/src/arm/64/mc.o" "-c" "src/arm/64/mc.S" with args "clang" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...
error: failed to compile `rav1e v0.3.4 (/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4)`, intermediate artifacts can be found at `/private/tmp/rav1e-20201229-30273-pmvhow/rav1e-0.3.4/target`

Caused by:
  build failed
```

I'm not sure what is causing this error. Did I miss another patch that needs to be applied? Can you offer some suggestion as to how to best fix this?

**Comment by lu-zero** [comment] 2020-12-29 09:23
Your version of `clang` seems getting a bogus target triple. How are you building rav1e exactly?

**Comment by fxcoudert** [comment] 2020-12-29 09:37
```
cargo install --locked --root /opt/homebrew/Cellar/rav1e/0.3.4 --path .
```

Full build logs are there: https://pipelines.actions.githubusercontent.com/revSbsLpzrFApLL6BmCvScWt72tRe3wYUv7fCdCtThtI5bydk7/_apis/pipelines/1/runs/113529/signedlogcontent/18?urlExpires=2020-12-29T09%3A37%3A51.1033786Z&urlSigningMethod=HMACV1&urlSignature=SAC405q4PwBD1ROlwv9z2WOEs5JIKEa%2F4rTwmEwtzJQ%3D

**Comment by lu-zero** [comment] 2020-12-29 09:38
what happens when you install the current master?

**Comment by lu-zero** [comment] 2020-12-29 09:39
btw:
```
value | "Uri expired"
```

**Comment by fxcoudert** [comment] 2020-12-29 09:45
Logs URL fixed above. I can't really install from master right now, I don't have access to a local ARM machine, it's Homebrew's CI.

**Comment by lu-zero** [comment] 2020-12-29 13:02
I can tell you that the clang problem seems related to Apple botching it for catalina. Even
```
clang -arch arm64 hello.c
```
Would fail.

On big sur 
```
cargo +nightly  build --target aarch64-apple-darwin
```

Works as intended.

**Comment by nilleb** [comment] 2020-12-29 20:30
@fxcoudert a `brew install --HEAD -s rav1e` works fine, too

**Comment by aimileus** [comment] 2020-12-30 09:59
A manual build of 0.3.4 with 64051920e674af6fe56f52c2a4cf99bc3a7287e8 backported (using Homebrew's Rust) compiles fine. It seems like some Homebrew/superenv issue.

**Comment by nilleb** [comment] 2020-12-30 20:38
@fxcoudert  evidence suggests that the `--locked` argument (part of `*std_cargo_args` in the rav1e formula) originates the problem you are experiencing.

> The --locked flag can be used to force Cargo to use the packaged Cargo.lock file if it is available. This may be useful for ensuring reproducible builds, to use the exact same set of dependencies that were available when the package was published. It may also be useful if a newer version of a dependency is published that no longer builds on your system, or has other problems. The downside to using --locked is that you will not receive any fixes or updates to any dependency. Note that Cargo did not start publishing Cargo.lock files until version 1.37, which means packages published with prior versions will not have a Cargo.lock file available.

So, looks like the Cargo.lock included with rav1e is the source of your problems.
So, adding a `unlink "Cargo.lock"` in the rav1e formula could help you.

**Comment by nilleb** [comment] 2020-12-30 20:46
Hey @lu-zero I think you can safely close this ;)

**Comment by lu-zero** [comment] 2020-12-30 22:18
I'll make a 0.4.0-beta soon, hopefully that will help you.

**Comment by fxcoudert** [comment] 2020-12-31 09:04
> This may be useful for ensuring reproducible builds

This is the point we use `--locked`, actually. To build with known-good versions of dependencies, and not “whatever is available at the moment”.

**Comment by nilleb** [comment] 2020-12-31 09:07
@fxcoudert then you should take in consideration that at the moment that 0.3.4 was available, Apple Silicon didn't exist, and that rav1e dependencies were not considering that eventuality. If you wish to have a patched Cargo.lock, then it is possible, but you shall find the good versions of all the rav1e dependencies supporting Apple SIlicon.

Otherwise, you could consider waiting for 0.4.0-beta, as @lu-zero says.

**Comment by lu-zero** [comment] 2020-12-31 09:51
Help in getting a proper 0.3.5 welcome (it requires some work to update the dependencies). 

I can roll a low effort 0.3.5 with just the asm patch and a version bump assuming that's enough for your use-case.

**Comment by aimileus** [comment] 2020-12-31 09:54
As far as I can see, the only dependency that needs updating is cc. With this applied patch, both brew install and brew test succeed.

```
diff --git a/Cargo.lock b/Cargo.lock
index b3643230..b16af5d5 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -199,9 +199,9 @@ dependencies = [
 
 [[package]]
 name = "cc"
-version = "1.0.59"
+version = "1.0.66"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "66120af515773fb005778dc07c261bd201ec8ce50bd6e7144c927753fe013381"
+checksum = "4c0496836a84f8d0495758516b8621a622beb77c0fed418570e50764093ced48"
 dependencies = [
  "jobserver",
 ]
diff --git a/build.rs b/build.rs
index 64577795..dddc538b 100644
--- a/build.rs
+++ b/build.rs
@@ -82,6 +82,9 @@ fn build_asm_files() {
   {
     let dest_path = Path::new(&out_dir).join("config.h");
     let mut config_file = File::create(dest_path).unwrap();
+    if env::var("CARGO_CFG_TARGET_OS").unwrap() == "macos" {
+      config_file.write(b" #define PREFIX 1\n").unwrap();
+    }
     config_file.write(b" #define PRIVATE_PREFIX rav1e_\n").unwrap();
     config_file.write(b" #define ARCH_AARCH64 1\n").unwrap();
     config_file.write(b" #define ARCH_ARM 0\n").unwrap();
```

**Comment by lu-zero** [comment] 2021-03-30 15:47
This should be fine to close now, please reopen if there are other problems.

**Closed by lu-zero** 2021-03-30 15:47 UTC
