### ISSUE TITLE
nasm relocation R_X86_64_PC32 leads to a link failure

### ISSUE THREAD

**Issue by bitbytebit-cr** [xiph/rav1e#1805] opened 2019-10-29 18:24 UTC
I keep getting this compile failure when building ever since a week ago or so. It seems to have come about when the assembly from dav1d was added I suspect. Can provide more information as requested...

     Running `rustc --edition=2018 --crate-name rav1e src/lib.rs --color never --crate-type lib --crate-type staticlib --emit=dep-info,link -C opt-level=3 -C codegen-units=1 -C debuginfo=2 --crate-type staticlib --crate-type cdylib --cfg cargo_c -C link-arg=-Wl,-soname,librav1e.so.0 --cfg 'feature="asm"' --cfg 'feature="better-panic"' --cfg 'feature="binaries"' --cfg 'feature="cc"' --cfg 'feature="clap"' --cfg 'feature="default"' --cfg 'feature="ivf"' --cfg 'feature="nasm-rs"' --cfg 'feature="pretty_env_logger"' --cfg 'feature="scan_fmt"' --cfg 'feature="signal-hook"' --cfg 'feature="signal_support"' --cfg 'feature="y4m"' -C metadata=bd84de2a097a3463 -C extra-filename=-bd84de2a097a3463 --out-dir /mob/www/perceptual_hash_encoder/rav1e/target/release/deps -L dependency=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps --extern arg_enum_proc_macro=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libarg_enum_proc_macro-022e54e70af6d3f5.so --extern arrayvec=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libarrayvec-cfbaca1187ba1622.rlib --extern better_panic=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbetter_panic-1d3f8d0026f1d960.rlib --extern bincode=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbincode-f7f72a1387e9b498.rlib --extern bitstream_io=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbitstream_io-37b72d9bef0dbe47.rlib --extern cfg_if=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libcfg_if-58dce88b4b91f3c6.rlib --extern clap=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libclap-91d06aa45746f297.rlib --extern err_derive=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liberr_derive-d0caacc6904ad32e.so --extern itertools=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libitertools-18bd4614187911c4.rlib --extern ivf=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libivf-d834bdb40bc4b1ff.rlib --extern libc=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liblibc-bea7fa9d2f0d7e9e.rlib --extern log=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liblog-1aff90bc151d527c.rlib --extern num_derive=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libnum_derive-48664e2b95de1e59.so --extern num_traits=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libnum_traits-e0ad2f542ff103ac.rlib --extern paste=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libpaste-2babf8c106902f9a.rlib --extern pretty_env_logger=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libpretty_env_logger-d98887a1f53ee67a.rlib --extern rayon=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/librayon-05bcea6b655a6512.rlib --extern scan_fmt=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libscan_fmt-6286d2ac1dacfbaa.rlib --extern serde=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libserde-316f6d92bd255ba4.rlib --extern serde_derive=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libserde_derive-04f0f28f6ad87c36.so --extern signal_hook=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libsignal_hook-6af32bc6e5790a93.rlib --extern simd_helpers=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libsimd_helpers-26cb6ef74ee6e90a.so --extern y4m=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liby4m-73fe30505e9e1fd4.rlib -L /mob/www/perceptual_hash_encoder/rav1e/target/release/build/rav1e-ec1139f46015869c/out --cfg nasm_x86_64 -l static=rav1easm -L native=/mob/www/perceptual_hash_encoder/rav1e/target/release/build/backtrace-sys-5687cc1fddb7093d/out`
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/rav1e-bd84de2a097a3463.rav1e.5nfwsf44-cgu.0.rcgu.o" "-o" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/librav1e-bd84de2a097a3463.so" "-Wl,--version-script=/tmp/rustc3UioTW/list" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/rav1e-bd84de2a097a3463.4youszm1ybf1rd5m.rcgu.o" "-Wl,--gc-sections" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps" "-L" "/mob/www/perceptual_hash_encoder/rav1e/target/release/build/rav1e-ec1139f46015869c/out" "-L" "/mob/www/perceptual_hash_encoder/rav1e/target/release/build/backtrace-sys-5687cc1fddb7093d/out" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lrav1easm" "-Wl,--no-whole-archive" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libpaste-2babf8c106902f9a.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libitertools-18bd4614187911c4.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/librayon-05bcea6b655a6512.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/librayon_core-bdda035b736655f6.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libnum_cpus-e76561ff3a0d7ef8.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libcrossbeam_queue-8b9301456eab1b41.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libeither-f9e9fade7e9e8c0a.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libcrossbeam_deque-06619381945f2f1a.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libcrossbeam_epoch-0c52390048b1caf9.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libscopeguard-0c36538283c4299b.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libmemoffset-cfd99279653d5bdb.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libcrossbeam_utils-0ba3b8939686dbff.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liblazy_static-e1ad51b79e03f794.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libarrayvec-f8eecaccf02e78e3.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libnodrop-ebec3b79a6df5855.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbincode-f7f72a1387e9b498.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libserde-316f6d92bd255ba4.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbyteorder-54c3c5d2121d016c.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libarrayvec-cfbaca1187ba1622.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbitstream_io-37b72d9bef0dbe47.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libnum_traits-e0ad2f542ff103ac.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liblibc-bea7fa9d2f0d7e9e.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liblog-1aff90bc151d527c.rlib" "/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libcfg_if-58dce88b4b91f3c6.rlib" "-Wl,--start-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-66f1e3f3db8dd40e.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-30a4f9a1052675ab.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-527e71ff85fb2ff2.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-205c3694f0205189.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-2880a000beab0127.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-94ba47af98acfb3d.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-f762e9f6d64aa6e1.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-920916a8f9546f69.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-170df59c19f23e17.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-5480377ae50f979a.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-c539f5fd60728f16.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-e3e12fcd3977c7d9.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-52b6f57e7c06f96d.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-46463f46c644fe4a.rlib" "-Wl,-Bdynamic" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil" "-shared" "-Wl,-soname,librav1e.so.0"
  = note: /bin/ld: /mob/www/perceptual_hash_encoder/rav1e/target/release/build/rav1e-ec1139f46015869c/out/librav1easm.a(ipred.o): relocation R_X86_64_PC32 against symbol `rav1e_dr_intra_derivative' can not be used when making a shared object; recompile with -fPIC
          /bin/ld: final link failed: Bad value
          collect2: error: ld returned 1 exit status

error: aborting due to previous error

error: Could not compile `rav1e`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name rav1e src/lib.rs --color never --crate-type lib --crate-type staticlib --emit=dep-info,link -C opt-level=3 -C codegen-units=1 -C debuginfo=2 --crate-type staticlib --crate-type cdylib --cfg cargo_c -C link-arg=-Wl,-soname,librav1e.so.0 --cfg 'feature="asm"' --cfg 'feature="better-panic"' --cfg 'feature="binaries"' --cfg 'feature="cc"' --cfg 'feature="clap"' --cfg 'feature="default"' --cfg 'feature="ivf"' --cfg 'feature="nasm-rs"' --cfg 'feature="pretty_env_logger"' --cfg 'feature="scan_fmt"' --cfg 'feature="signal-hook"' --cfg 'feature="signal_support"' --cfg 'feature="y4m"' -C metadata=bd84de2a097a3463 -C extra-filename=-bd84de2a097a3463 --out-dir /mob/www/perceptual_hash_encoder/rav1e/target/release/deps -L dependency=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps --extern arg_enum_proc_macro=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libarg_enum_proc_macro-022e54e70af6d3f5.so --extern arrayvec=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libarrayvec-cfbaca1187ba1622.rlib --extern better_panic=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbetter_panic-1d3f8d0026f1d960.rlib --extern bincode=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbincode-f7f72a1387e9b498.rlib --extern bitstream_io=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libbitstream_io-37b72d9bef0dbe47.rlib --extern cfg_if=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libcfg_if-58dce88b4b91f3c6.rlib --extern clap=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libclap-91d06aa45746f297.rlib --extern err_derive=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liberr_derive-d0caacc6904ad32e.so --extern itertools=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libitertools-18bd4614187911c4.rlib --extern ivf=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libivf-d834bdb40bc4b1ff.rlib --extern libc=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liblibc-bea7fa9d2f0d7e9e.rlib --extern log=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liblog-1aff90bc151d527c.rlib --extern num_derive=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libnum_derive-48664e2b95de1e59.so --extern num_traits=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libnum_traits-e0ad2f542ff103ac.rlib --extern paste=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libpaste-2babf8c106902f9a.rlib --extern pretty_env_logger=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libpretty_env_logger-d98887a1f53ee67a.rlib --extern rayon=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/librayon-05bcea6b655a6512.rlib --extern scan_fmt=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libscan_fmt-6286d2ac1dacfbaa.rlib --extern serde=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libserde-316f6d92bd255ba4.rlib --extern serde_derive=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libserde_derive-04f0f28f6ad87c36.so --extern signal_hook=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libsignal_hook-6af32bc6e5790a93.rlib --extern simd_helpers=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/libsimd_helpers-26cb6ef74ee6e90a.so --extern y4m=/mob/www/perceptual_hash_encoder/rav1e/target/release/deps/liby4m-73fe30505e9e1fd4.rlib -L /mob/www/perceptual_hash_encoder/rav1e/target/release/build/rav1e-ec1139f46015869c/out --cfg nasm_x86_64 -l static=rav1easm -L native=/mob/www/perceptual_hash_encoder/rav1e/target/release/build/backtrace-sys-5687cc1fddb7093d/out` (exit code: 1)
Error: Kind(InvalidInput)
make: *** [rav1elib] Error 1

**Comment by shssoichiro** [comment] 2019-10-29 18:37
I occasionally have random failures due to linker errors, which are often resolved by doing a `cargo clean`.

If you're tried that and are still seeing failures, could you post which version of Rustc and Nasm you have on your machine?

**Comment by bitbytebit-cr** [comment] 2019-10-29 21:04
So I have used cargo clean and re-cloned, this is the set of commands I run usually..
        cargo build --release &&         sudo cargo cinstall --release

It fails on the cargo cinstall it seems.

Here are the versions...

cargo 1.37.0
rustc 1.37.0
NASM version 2.14.03rc2 compiled on Sep 10 2019

**Comment by shssoichiro** [comment] 2019-10-29 21:40
I was able to reproduce this with the same commands on my machine with Rust 1.38.0. It looks like this is a breakage in rav1e's clib.

**Comment by tdaede** [comment] 2019-10-29 21:50
Likely introduced by the recent dav1d asm merges. Might be fixed by the most recent one?

**Comment by shssoichiro** [comment] 2019-10-30 02:20
This is still broken as of #1802.

**Closed** 2019-10-31 21:53 UTC
Labels: blocker, bug, high priority
