### ISSUE TITLE
Overwrite prompt missing.

### ISSUE THREAD

**Issue by qrpnxz** [xiph/rav1e#2295] opened 2020-05-12 23:36 UTC
Please add something to the effect of

`Are you sure you want to override "preciousbits.ivf"? [y/N]`

I just got burned by the lack of this little tidbit.
Thanks.

**Comment by tdaede** [comment] 2020-05-18 08:24
We can either do an interactive prompt, with a -y override, or an uninteractive error, with a -f override. Opinions?

**Comment by gnafuthegreat** [comment] 2020-05-21 11:43
My vote would be for an interactive prompt with a -y override, similar to ffmpeg.

**Comment by Urhengulas** [comment] 2020-05-28 11:12
Since the issue is assigned to @Dayof I guess it's taken?

**Closed** 2020-05-30 05:09 UTC
Labels: enhancement, good first issue
