### ISSUE TITLE
js_api CI is broken

### ISSUE THREAD

**Issue by rzumer** [xiph/rav1e#2570] opened 2020-10-11 21:06 UTC
It stopped working recently, seemingly due to Rust 1.47.

```
--- node::simple_encoding output ----
    JS exception that was thrown:
        RuntimeError: memory access out of bounds
            at alloc::collections::btree::node::LeafNode<K,V>::new::h685ae83d67344358 (<anonymous>:wasm-function[1300]:0x2510fe)
            at alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::KV>::split::h8014b2ce66798ec2 (<anonymous>:wasm-function[962]:0x22d603)
            at alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert::h67a96866bc4d3fd1 (<anonymous>:wasm-function[285]:0x1a351c)
            at alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert_recursing::hbbd9d6703cd1767e (<anonymous>:wasm-function[256]:0x1951ad)
            at alloc::collections::btree::map::VacantEntry<K,V>::insert::hfb77e3207a9735f3 (<anonymous>:wasm-function[825]:0x21b24c)
            at alloc::collections::btree::map::BTreeMap<K,V>::insert::hd61c081a15b4dc8a (<anonymous>:wasm-function[755]:0x210c53)
            at rav1e::api::internal::ContextInner<T>::set_frame_properties::h23fed24ddf62cf4e (<anonymous>:wasm-function[209]:0x179635)
            at rav1e::api::internal::ContextInner<T>::compute_frame_invariants::h3a223707410e2d12 (<anonymous>:wasm-function[1739]:0x27382e)
            at rav1e::api::internal::ContextInner<T>::send_frame::habb44e1d969df412 (<anonymous>:wasm-function[237]:0x18affe)
            at rav1e::api::context::Context<T>::send_frame::{{closure}}::h8d589cf3fc337fbe (<anonymous>:wasm-function[3312]:0x2bffa5)
```

**Comment by Urhengulas** [comment] 2020-10-12 14:48
Thanks @lu-zero for pinging. I will have a look in the next days.

**Comment by lu-zero** [comment] 2020-10-13 14:27
Thank you :)

**Comment by Luni-4** [comment] 2020-10-15 09:37
@Urhengulas 

`Rust` version 1.47 breaks the `js_api` CI for an unknown reason

**Comment by Urhengulas** [comment] 2020-12-14 12:15
Hi hi 👋🏾 ,
Currently having a bit of free time and am looking at this issue.

The stack trace states that it's some problem with the `frame_data` propterty of the `rav1e::api::internal::ContextInner`, which is a `BTreeMap<u64, FrameData<T>>`. So far I couldn't figure out what the exact problem is, and am trying to reproduce the bug with a more nuclear example to open an issue on `wasm-bindgen`.

Looking at the release notes of `rust 1.47` ([_release notes_](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1480-2020-11-19)) the only change which seems possible to cause the issue is the upgrade to `llvm 11` by default, but I didn't check that yet.

**Comment by barrbrain** [comment] 2021-01-28 06:21
Now that the JS API has moved to <https://github.com/rust-av/rav1e_js>, we should open an issue there to continue this work.
Unfortunately, we cannot simply transfer the issue because the repositories have different owners.
Closing since the JS API was removed in #2649.

**Closed by barrbrain** 2021-01-28 06:21 UTC
Labels: CI
