### ISSUE TITLE
1 and 2 pixel PNG to AVIF conversion produces no output with Rav1e

### ISSUE THREAD

**Issue by adityapatadia** [xiph/rav1e#2541] opened 2020-09-15 07:01 UTC
When 1 and 2 pixel wide images are converted to AVIF through Rav1e, they don't produce correct output. Encoding through libaom works fine. Please check this issue: https://github.com/strukturag/libheif/issues/311

**Comment by barrbrain** [comment] 2020-09-15 07:06
This is a duplicate of #2518.

**Closed** 2020-09-15 07:09 UTC
