### ISSUE TITLE
Rav1e doesn't respect MIN_KEYFRAME_INTERVAL

### ISSUE THREAD

**Issue by figgis** [xiph/rav1e#1497] opened 2019-07-24 22:05 UTC
I have a 50 frame sequence and I'd like the first frame only to be a keyframe.
-i 100 and -I defaulting to 240 should work but I get 4 keyframes

```
cargo run --release --bin rav1e -- in.y4m -i 100 -o out.ivf
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/rav1e in.y4m -i 100 -o out.ivf`
1280x720 @ 25/1 fps
encoded 54 frames, 0.207 fps, 1096.35 Kb/s                    
Key Frames:      4    avg size:   48216 B
Inter:          50    avg size:    2063 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B

```

**Comment by rzumer** [comment] 2019-07-24 22:29
It looks like `--keyint` (max interval) must also be set to 1 in order for it to be respected.

**Comment by rzumer** [comment] 2019-07-24 22:39
Testing on current master, `--min-keyint 200` does code only one keyframe.

**Comment by figgis** [comment] 2019-07-25 15:04
With  `-i 200 --keyint 200` I get:

```
1280x720 @ 25/1 fps
encoded 54 frames, 0.222 fps, 1159.65 Kb/s                    
Key Frames:      4    avg size:   47987 B
Inter:          50    avg size:    2423 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
```

Problem seems to be the `SceneChangeDetector`, if I disable that I get:

```
1280x720 @ 25/1 fps
encoded 54 frames, 0.235 fps, 639.16 Kb/s                    
Key Frames:      1    avg size:   40443 B
Inter:          53    avg size:    2493 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B

```

**Comment by shssoichiro** [comment] 2019-07-26 03:00
I suspect #1481 may fix this.

**Comment by shssoichiro** [comment] 2019-07-31 13:42
@figgis Could you retest this against latest master, now that #1481 has been merged?

**Comment by figgis** [comment] 2019-07-31 15:21
Tested on master `3dcb26667f98a014d582dac40b7dcb65291f3425` and it has definitely improved.
```
1280x720 @ 25/1 fps
encoded 54 frames, 0.195 fps, 732.96 Kb/s                    
Key Frames:      2    avg size:   39751 B
Inter:          52    avg size:    2276 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
```

First and last frames are key frames.

**Comment by shssoichiro** [comment] 2019-08-01 00:50
Seems odd that the last frame is being selected. Would you be able to share the sample that you're testing against?

**Comment by figgis** [comment] 2019-08-01 11:57
I don't think this has anything to do with the src. I did some simple bisecting and when using `-i 200 --keyint 200 -l 22` I get 1 key frame. When using `-i 200 --keyint 200 -l 23` instead, I get 2 key frames.

**Comment by shssoichiro** [comment] 2019-08-01 19:20
I'm not able to reproduce this with the test clip I tried.

```
╰─ target/release/rav1e -o /dev/null -i 200 -I 200 -l 22 ~/Downloads/ducks_take_off_360p50.y4m
640x360 @ 50/1 fps
encoded 22/22 frames, 0.922 fps, 3757.13 Kb/s, est. size: 0.20 MB, est. time: 0 s
Key Frames:      1    avg size:   41201 B
Inter:          21    avg size:    7878 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
```

```
╰─ target/release/rav1e -o /dev/null -i 200 -I 200 -l 23 ~/Downloads/ducks_take_off_360p50.y4m
640x360 @ 50/1 fps
encoded 23/23 frames, 0.906 fps, 3805.41 Kb/s, est. size: 0.21 MB, est. time: 0 s
Key Frames:      1    avg size:   41201 B
Inter:          22    avg size:    8073 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
```

```
╰─ target/release/rav1e -o /dev/null -i 200 -I 200 -l 199 ~/Downloads/ducks_take_off_360p50.y4m
640x360 @ 50/1 fps
encoded 199/199 frames, 0.534 fps, 4434.71 Kb/s, est. size: 2.10 MB, est. time: 0 s
Key Frames:      1    avg size:   41176 B
Inter:         198    avg size:   10934 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
```

**Comment by figgis** [comment] 2019-08-01 21:16
Interesting

```
 -i 200 --keyint 200 -l 23 -o out_23.ivf`
1280x720 @ 25/1 fps
encoded 23/23 frames, 0.203 fps, 959.61 Kb/s, est. size: 0.11 MB, est. time: 0 s                      
Key Frames:      2    avg size:   44216 B
Inter:          21    avg size:    1043 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
```

```
 -i 200 --keyint 200 -l 22 -o out_22.ivf`
1280x720 @ 25/1 fps
encoded 22/22 frames, 0.210 fps, 568.63 Kb/s, est. size: 0.06 MB, est. time: 0 s                      
Key Frames:      1    avg size:   40626 B
Inter:          21    avg size:    1043 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B

```

You can download my sequence from [here](https://send.firefox.com/download/b548ce6708fcb23d/#jEqQTQUaq1Zl5W0TcLvyIA)

**Closed** 2019-08-06 02:45 UTC
Labels: bug
