### ISSUE TITLE
A debug_assert fails with --speed 0

### ISSUE THREAD

**Issue by colbyn** [xiph/rav1e#1185] opened 2019-04-05 04:27 UTC
Example output:
```
1500x1010 @ 25/1 fps
thread '<unnamed>' panicked at 'assertion failed: (tx_size, tx_type) ==
    rdo_tx_size_type(fi, fs, cw, bsize, bo, mode_luma, ref_frames, mvs, skip)', src/encoder.rs:1541:3
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
I’m not sure if this is of any interest to you guys. I considered a PR with the line commented out https://github.com/colbyn/rav1e but since the fix is quite simple I thought I’d just post an issue instead.

**Comment by ycho** [comment] 2019-04-10 16:17
@colbyn, thanks for reporting this! This MATTERS to US of course.
If possible, can you please share the encoding options as well?

**Comment by colbyn** [comment] 2019-04-12 18:20
Certainly. I have been more explicit.

Here is [the commit](https://github.com/colbyn/rav1e/commit/d681400c11840397a3d7618c942ce2532e8df1a5) where I commented out the assertion.

To elaborate if anyone is unaware, to my understanding unlike the `std::assert` macro the `std::debug_assert` will generally only panic in dev builds, so binaries compiled with the `--release` flag won't be affected (just in case this caused confusion). Although I suppose this is really only something that will effect those experimenting with the codebase. 

Here is the full output:
```
▶ cargo run --bin rav1e -- /Users/colbyn/Desktop/lab/ef036c4c.y4m -o /Users/colbyn/Desktop/lab/ef036c4c.ivf --speed 0
   Compiling proc-macro2 v0.4.27
   Compiling unicode-xid v0.1.0
   Compiling libc v0.2.51
   Compiling arrayvec v0.4.10
   Compiling syn v0.15.30
   Compiling memchr v2.2.0
   Compiling cfg-if v0.1.7
   Compiling nodrop v0.1.13
   Compiling lazy_static v1.3.0
   Compiling scopeguard v0.3.3
   Compiling memoffset v0.2.1
   Compiling ucd-util v0.1.3
   Compiling regex v0.2.11
   Compiling autocfg v0.1.2
   Compiling serde v1.0.90
   Compiling rayon-core v1.4.1
   Compiling ryu v0.2.7
   Compiling byteorder v1.3.1
   Compiling pkg-config v0.3.14
   Compiling num-traits v0.2.6
   Compiling nasm-rs v0.1.3 (https://github.com/tdaede/nasm-rs?branch=msvc-OUT#c134ca85)
   Compiling rand_core v0.4.0
   Compiling utf8-ranges v1.0.2
   Compiling rayon v1.0.3
   Compiling unicode-width v0.1.5
   Compiling bitflags v1.0.4
   Compiling rustc-demangle v0.1.13
   Compiling bitstream-io v0.8.2
   Compiling itoa v0.4.3
   Compiling either v1.5.2
   Compiling y4m v0.3.2
   Compiling crossbeam-utils v0.2.2
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.5.6
   Compiling rand_core v0.3.1
   Compiling backtrace v0.3.15
   Compiling textwrap v0.10.0
   Compiling ivf v0.1.0 (/Users/colbyn/Resources/rav1e/ivf)
   Compiling rav1e v0.1.0 (/Users/colbyn/Resources/rav1e)
   Compiling crossbeam-epoch v0.3.1
   Compiling clap v2.32.0
   Compiling num_cpus v1.10.0
   Compiling rand v0.5.6
   Compiling aho-corasick v0.6.10
   Compiling crossbeam-deque v0.2.0
   Compiling quote v0.6.11
   Compiling serde_json v1.0.39
   Compiling bincode v1.0.1
   Compiling scan_fmt v0.1.3
   Compiling proc-macro-hack v0.5.4
   Compiling serde_derive v1.0.90
   Compiling arg_enum_proc_macro v0.1.1
   Compiling paste-impl v0.1.5
   Compiling paste v0.1.5
    Finished dev [optimized + debuginfo] target(s) in 2m 08s
     Running `target/debug/rav1e /Users/colbyn/Desktop/lab/ef036c4c.y4m -o /Users/colbyn/Desktop/lab/ef036c4c.ivf --speed 0`
768x1024 @ 25/1 fps
thread '<unnamed>' panicked at 'assertion failed: (tx_size, tx_type) ==
    rdo_tx_size_type(fi, fs, cw, bsize, bo, mode_luma, ref_frames, mvs, skip)', src/encoder.rs:1541:3
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Attached is the given input file from the above snippet (although zipped, the uploader apparently doesn't like raw y4m files).
[ef036c4c.y4m.zip](https://github.com/xiph/rav1e/files/3074650/ef036c4c.y4m.zip)

**Comment by colbyn** [comment] 2019-04-12 18:21
Oh and the commit hash is: 70005e353aa8ce21e3ecd257c927f71d4012a117

**Comment by ycho** [comment] 2019-06-13 21:02
@colbyn: Can you check whether this still happens please?

**Comment by colbyn** [comment] 2019-06-15 01:35
Sure. Do you have a particular branch in mind? Running from the latest master yields this:
```
▶ cargo run --release --bin rav1e -- /Users/colbyn/Desktop/ef036c4c.y4m -o /Users/colbyn/Desktop/ef036c4c.ivf
    Finished release [optimized] target(s) in 0.15s
     Running `target/release/rav1e /Users/colbyn/Desktop/ef036c4c.y4m -o /Users/colbyn/Desktop/ef036c4c.ivf`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by rzumer** [comment] 2019-07-24 15:54
My attempt to reproduce:
```
rzumer@haru:~/dev/rav1e$ cargo run --bin rav1e --features=binaries -- ef036c4c.y4m -o enc_file.ivf -s 0
    Finished dev [optimized + debuginfo] target(s) in 0.06s
     Running `target/debug/rav1e ef036c4c.y4m -o enc_file.ivf -s 0`
768x1024 @ 25/1 fps
encoded 1 frames, 0.012 fps, 27044.80 Kb/s                    
Key Frames:      1    avg size:  135224 B
Inter:           0    avg size:       0 B
Intra Only:      0    avg size:       0 B
Switch:          0    avg size:       0 B
```

Sorry to ask again, but can you try running it once more on the master branch, @colbyn? This may have been fixed recently.

**Comment by ycho** [comment] 2019-07-24 17:15
@rzumer, the reason why the assert fail disappear now might be the disabled partition tx (2019/06/21, 44d7ffb777f76b39502fbabd4f77bc1e8bc4e0ba ) since it is turned on for speed 0,1,2,3.

**Comment by rzumer** [comment] 2019-07-24 17:22
@ycho OK; since we have #1391 keeping track of the work required to re-enable it, maybe we can close this issue, unless you think it is unrelated.

**Comment by ycho** [comment] 2019-07-24 17:25
> @ycho OK; since we have #1391 keeping track of the work required to re-enable it, maybe we can close this issue, unless you think it is unrelated.

You are exactly correct, I also think #1391 (and #1200 as mentioned) seems related to it.
Thanks for following on this issue!

**Comment by rzumer** [comment] 2019-07-24 19:29
Great, then I will close this issue; if we re-enable features that bring back this encoding error, please reopen.

**Closed by rzumer** 2019-07-24 19:29 UTC
Labels: bug
