### ISSUE TITLE
Very Bad Edge Artifacting on Sintel

### ISSUE THREAD

**Issue by dwbuiten** [xiph/rav1e#1262] opened 2019-05-07 14:13 UTC
Output file: http://chromashift.org/sintel.720.mp4 - look at ~11:52.
Encoding parameters: Encoded via crav1e API, with: `speed=2:tile_cols_log2=1:tile_rows_log2=1:quantizer=255:bitrate=2252800:key_frame_interval=72:min_key_frame_interval=72`

I can provide the exact lossless input sequence (with our zimg-based resizing, etc.) if that is useful. Just didn't yet because Big Files.

**Comment by tdaede** [comment] 2019-05-07 22:15
Looks like it's happening through the whole movie, should be able to reproduce with a much shorter sequence like Shields.

Kinda looks like the skip decision is broken.

**Comment by tdaede** [comment] 2019-05-23 01:57
So playing with this more I think it's actually a rate control issue. I didn't dump the quantizers in the mp4 to be sure, but I was unable to reproduce this without rate control enabled. The right edge looks bad because that's new content coming in at the old quantizer - the rest of the frame is just a pan so it's going to look good as it's just motion compensated old image data.

**Comment by tdaede** [comment] 2019-05-23 01:57
... which means, now that we have landed some rate control fixes, could you try encoding it again and see if it is still present?

**Comment by dwbuiten** [comment] 2019-05-23 13:25
@tdaede I will re-run it when I push the clmap fix, at least. Ideally I'd like the frame subtype fix in, but I do not know its status.

**Comment by dwbuiten** [comment] 2019-05-27 14:54
@tdaede will re-run a test, but i dont see how it can be rate control, since only edge blocks are affected; the rest of the frame looks fine...

**Comment by dwbuiten** [comment] 2019-05-30 12:10
@tdaede It did not go away. :(

**Comment by dwbuiten** [comment] 2019-05-30 12:11
http://chromashift.org/sintel.new.mp4

**Comment by dwbuiten** [comment] 2019-05-30 14:52
I can reproduce with a shorter (340 frame, 640x278) clip. Those specific artifacts are also visible on higher quantizer encodes (e.g. 190). The difference is the whole frame looks bad rather than just part of the frame, as it does with bitrate mode.

Relevant scroll back:
```
[15:01] < barrbrain> oh, it’s quite simple… those blocks are skip with motion vectors extending beyond the frame edge
[15:01] < Daemon404> o.o
[15:02] < Daemon404> could ratecontol really cause that?
[15:02] < barrbrain> the vertical lines are edge extension
[15:02] < barrbrain> rate control and/or RDO
[15:02] < Daemon404> i see
[15:02] < barrbrain> once RC is sane, probably just RDO
[15:02] < Daemon404> i mean
[15:02] < Daemon404> that doesnt help me fix it.
[15:02] < Daemon404> https://www.dropbox.com/s/u4yokqsvuctylin/edge.png?dl=0 <-- this is what it looks like when real bad
[15:03] < Daemon404> by fix it i mean "not in three weeks"...
[15:04] < barrbrain> I think it’s because it nails 90% of pixels in the block so the error at the edge averages out to small
[15:04] < Daemon404> any reason why this wouldnt manifest itself in quantizer mdoe?
[15:04] < Daemon404> mode*
[15:04] < Daemon404> im not quite following why
[15:06] < Daemon404> (might be a red herring... maybe i just didnt test the right quantizer)
[15:06] < barrbrain> it’s a 64x64 block, frame BaseQindex is 255 for the first 2 frames that it occurs
[15:07] < Daemon404> whats BaseQindex here
[15:07] < barrbrain> the luma AC quantizer index
[15:07] < barrbrain> max is 255
```

**Comment by dwbuiten** [comment] 2019-05-30 15:37
Here's a very simple way to reproduce:

Clip: http://chromashift.org/clip.y4m.xz
CLI: `--bitrate 512 --speed 4 --tile-cols-log2 1 --tile-rows-log2 1 -I 72 -i 72`

Tile options probably aren't useful, but I happened to test them.

The edge effect can also be seen in quantizer mode like:

CLI: `--quantizer 190 --speed 4 --tile-cols-log2 1 --tile-rows-log2 1 -I 72 -i 72`

It's not as noticable since in quantizer mode, the whole frame looks pretty bad. But the edge artifacts are still here.

**Comment by dwbuiten** [comment] 2019-05-30 17:20
Current hypothesis is that the keyframe chosen after that scene change is too large and while it provides a very good reference frame for the subsequent frames, their quantizr is still 200-255, so the new (edge) bits look terrible.

**Comment by ycho** [comment] 2019-05-31 18:21
> Current hypothesis is that the keyframe chosen after that scene change is too large and while it provides a very good reference frame for the subsequent frames, their quantizr is still 200-255, so the new (edge) bits look terrible.
> 
> ```
> [18:21] <Daemon404> i bet it's affected partially by show_existing_frame
> [18:22] <Daemon404> cause the keyframe is huge, but it probably also counts the bits from the invisible frames -> next few frames have no bits
> ```

Right, with qindex = 255, I observed that the total # of bits for the frame was ~ 1000 bits! 1K!

**Comment by dwbuiten** [comment] 2019-06-03 20:53
@tdaede Should I close this, or do we care about the edge funniness on high quants (out of range MVs?).

**Comment by tdaede** [comment] 2019-06-03 21:01
Depends... does it look like there might be a better predictor available than what rav1e chose?

**Comment by dwbuiten** [comment] 2019-06-03 21:15
I would expect there is no much to choose from, since it's at the edge that's being revealed. Is it choosing the edge extension as a predictor (is that allowed?)?

**Comment by tdaede** [comment] 2019-06-03 21:21
If it chooses an out-of-frame MV, that's effectively what's happening.

**Comment by ycho** [comment] 2019-06-03 21:26
To get improved quality on those blocks, I believe it should have used smaller QP + chosen intra modes? I think that too large (in fact, largest possible has been chosen) QP is the root reason.

**Comment by dwbuiten** [comment] 2019-06-03 22:12
@ycho That problem has been fixed with https://github.com/xiph/rav1e/commit/40b2b0210045596e7f30bad4f8e77b71960f8b3b

The funny edge still exists in an e.g. quant 190 encode (but of course the whole frame looks bad too).

@tdaede Yeah... Not sure if anything better could exist? If you think not, we can close.

**Closed** 2019-06-08 15:54 UTC
Labels: bug, high priority
