### ISSUE TITLE
Add support for 128x128 superblocks

### ISSUE THREAD

**Issue by tmatth** [xiph/rav1e#1245] opened 2019-04-24 21:01 UTC
Will need to fix CDEF among other things:
https://github.com/xiph/rav1e/blob/ae5a21e86d8337b9851355eee3a61b2850028a21/src/cdef.rs#L438

It's possible that this FIXME is out of date and can be dropped.

**Comment by tmatth** [comment] 2019-04-24 21:27
Currently, this patch:
```
diff --git a/src/context.rs b/src/context.rs
index cdcf1d7..95082b4 100644
--- a/src/context.rs
+++ b/src/context.rs
@@ -47,7 +47,7 @@ const MAX_MIB_SIZE_LOG2: usize = (MAX_SB_SIZE_LOG2 - MI_SIZE_LOG2);
 pub const MAX_MIB_SIZE: usize = (1 << MAX_MIB_SIZE_LOG2);
 pub const MAX_MIB_MASK: usize = (MAX_MIB_SIZE - 1);
 
-const MAX_SB_SIZE_LOG2: usize = 6;
+const MAX_SB_SIZE_LOG2: usize = 7;
 pub const MAX_SB_SIZE: usize = (1 << MAX_SB_SIZE_LOG2);
 const MAX_SB_SQUARE: usize = (MAX_SB_SIZE * MAX_SB_SIZE);
 ```
fails on `./build.sh` with:
```
480x304 @ 30/1 fps
thread '<unnamed>' panicked at 'index out of bounds: the len is 486400 but the index is 531360', /home/tmatth/rav1e/src/plane.rs:570:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:211
             at src/libstd/panicking.rs:474
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   4: rust_begin_unwind
             at src/libstd/panicking.rs:308
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   7: rav1e::encoder::encode_tile
   8: rayon::iter::plumbing::bridge_producer_consumer::helper
   9: rav1e::encoder::encode_frame
  10: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  11: rayon_core::registry::WorkerThread::wait_until_cold
```

**Comment by rzumer** [comment] 2019-04-27 13:44
If I recall correctly there are a few things needed to implement 128x128 SB support, it is more involved than the other sizes.

I guess this is a duplicate of #71, so closing it as such, Feel free to reopen/swap the opened issue if needed.

**Closed by rzumer** 2019-04-27 13:44 UTC
